export const dapps = [
        {
          "name": "Empo",
          discord: "",
          image: "empo.jpg",
          url: "",
          description:"",
          tags: ["DEX", "DeFi"],
          Published: "Jul 19, 2022 6:53 AM",
          twitter: "https://twitter.com/Empo_Fi",
          status: "TBA",
          github: "",
          Docs: "",
          Npm: "",
        },
        {
          name: "Zaptos",
          discord: "https://discord.gg/zaptos",
          image: "zaptos.jpg",
          url: "",
          description:"",
          tags: ["DEX", "DeFi"],
          Published: "Jul 19, 2022 6:53 AM",
          twitter: "https://twitter.com/Empo_Fi",
          status: "TBA",
          github: "",
          Docs: "",
        },
        // {
        //   "name": "NjordFinance",
        //   "tags": "DeFi",
        //   "discord": "",
        //   "Published": "Jul 27, 2022 12:42 PM",
        //   "twitter": "https://twitter.com/NjordFinance",
        //   "status": "TBA",
        //   "logo": "",
        //   "Github": "",
        //   "Docs": "",
        //   "Npm": "",
        //   "k": "DEFI"
        // },
        // {
        //   "name": "Thala Labs",
        //   "tags": "DeFi",
        //   "discord": "",
        //   "Published": "Jul 21, 2022 7:50 PM",
        //   "twitter": "https://twitter.com/ThalaLabs",
        //   "status": "TBA",
        //   "logo": "",
        //   "Github": "",
        //   "Docs": "",
        //   "Npm": "",
        //   "k": "DEXDEFI"
        // },
        {
          "name": "1kx",
          "tags": ["DeFi", "Exchange"],
          "discord": "",
          "twitter": "https://twitter.com/1kxprotocol",
          "status": "Testnet",
          image: "1kx.jpg",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "DEXDEFI"
        },
        {
          "name": "ultima",
          "tags": "DEX, Exchange",
          "discord": "",
          "twitter": "https://twitter.com/ultimaprotocol",
          
          "status": "",
          "image": "ultima.jpg",
          "github": "",
          "docs": "",
          "Npm": "",
        },
        {
          "name": "AptosLend",
          "tags": ["Lending"],
          "discord": "",
          "Published": "Jul 30, 2022 2:14 PM",
          "twitter": "https://twitter.com/aptoslend",
          "status": "TBA",
          "image": "aptosLend.png",
          "github": "",
          "Docs": "",
          "Npm": "",
        },
        {
          "name": "Pontem Network",
          "tags": ["DEX", "DeFi", "Infrastructure", "Tools"],
          "discord": "https://discord.gg/kHWnQpBq",
          "Published": "Jul 19, 2022 5:48 AM",
          "twitter": "https://twitter.com/PontemNetwork",
          "status": "Testnet",
          "logo": "",
          "github": "",
          "image": "pontemNetwork.jpeg",
        },
        
        {
          "name": "Hanson",
          "tags": ["DeFi"],
          "description": "",
          "discord": "",
          "twitter": "https://twitter.com/hansondotso",
          "status": "TBA",
          "image": "",
          "github": "",
        },
        // {
        //   "name": "Laminar",
        //   "tags": ["DEX", "Orderbook"],
        //   "description": "",
        //   "discord": "https://discord.gg/h6Kx9pkp",
        //   "Published": "Jul 19, 2022 5:48 AM",
        //   "twitter": "https://twitter.com/LaminarMarkets",
        //   "status": "TBA",
        //   "logo": "",

        //   "github": "",
        //   "Docs": "",
        //   "Npm": "",
        //   "k": "DEXORDER"
        // },
        {
          "name": "Tsunami Finance",
          "tags": ["DeFi"],
          "discord": "",
          "Published": "Jul 25, 2022 10:00 AM",
          "twitter": "https://twitter.com/Tsunamifinance_",
          "status": "",
          "logo": "",
          "github": "",
          "Docs": "",
          "Npm": "",
          "k": "DEFI"
        },
        // {
        //   "name": "Switchboard",
        //   "tags": "Oracle",
        //   "discord": "",
        //   "Published": "Jul 19, 2022 6:28 AM",
        //   "twitter": "https://twitter.com/switchboardxyz",
        //   "status": "TBA",
        //   "logo": "",
        //   "github": "",
        //   "Docs": "",
        //   "Npm": "",
        //   "k": "ORACLE"
        // },
        // {
        //   "name": "Vial Protocol",
        //   "tags": "DeFi",
        //   "discord": "",
        //   "Published": "Jul 19, 2022 4:35 PM",
        //   "twitter": "https://twitter.com/vialprotocol",
        //   "status": "Testnet",
        //   "logo": "",
        //   "github": "",
        //   "Docs": "",
        //   "Npm": "",  
        //   "k": "DEFI"
        // },
        // {
        //   "name": "names.aptos",
        //   "tags": "Name Service, Tools",
        //   "discord": "",
        //   "Published": "Jul 19, 2022 6:28 AM",
        //   "twitter": "https://twitter.com/aptosnames",
        //   "status": "Testnet",
        //   "image": "",
        //   "github": "",
        //   "Docs": "",
        //   "Npm": "",
        //   "k": "NFTIdentity"
        // },
        {
          "name": "Hippo Labs",
          "tags": ["Aggregator", "DeFi", "Tools"],
          "description": "",
          "image": "hippoLabs.png",
          "discord": "",
          "Published": "Jul 19, 2022 6:22 AM",
          "twitter": "https://twitter.com/hippolabs__",
          "status": "",
          "logo": "",
          "github": "",
          "Docs": "",
          "Npm": "",
        },
        // {
        //   "name": "Aries Market - Decentralised Margin Trading",
        //   "tags": "DeFi",
        //   "discord": "https://discord.gg/h6Kx9pkp",
        //   "Published": "Jul 19, 2022 6:05 AM",
        //   "twitter": "https://twitter.com/AriesMarkets",
        //   "status": "TBA",
        //   "logo": "",
        //   "github": "",
        //   "Docs": "",
        //   "Npm": "",
        //   "k": "PERPNetworkORDER"
        // },
        // {
        //   "name": "Fewcha Wallet - crypto wallet for Aptos",
        //   "tags": "Wallet",
        //   "discord": "https://discord.gg/HRbMWmhm",
        //   "Published": "Jul 19, 2022 5:45 AM",
        //   "twitter": "https://twitter.com/FewchaWallet",
        //   "status": "Testnet",
        //   "logo": "",
        //   "github": "",
        //   "Docs": "",
        //   "Npm": "",
        //   "k": "WALLET"
        // },
        // {
        //   "name": "Mariana Exchange",
        //   "tags": "DeFi, Exchange",
        //   "discord": "",
        //   "Published": "Jul 27, 2022 12:45 PM",
        //   "twitter": "https://twitter.com/marianaexchange",
        //   "status": "TBA",
        //   "logo": "",
        //   "github": "",
        //   "Docs": "",
        //   "Npm": "",
        //   "k": "DEXDEFI"
        // },
        // {
        //   "name": "Paymagic",
        //   "tags": "Dao",
        //   "discord": "",
        //   "Published": "Jul 19, 2022 6:28 AM",
        //   "twitter": "https://twitter.com/paymagic_",
        //   "status": "TBA",
        //   "logo": "",
        //   "github": "",
        //   "Docs": "",
        //   "Npm": "",
        //   "k": "DAO"
        // },
        // {
        //   "name": "Econia",
        //   "tags": "DeFi, Orderbook",
        //   "discord": "https://discord.gg/ydAeGtrW",
        //   "Published": "Jul 19, 2022 6:20 AM",
        //   "twitter": "https://twitter.com/EconiaLabs",
        //   "status": "TBA",
        //   "logo": "",
        //   "github": "",
        //   "Docs": "",
        //   "Npm": "",
        //   "k": "DEXORDERNetwork"
        // },
        // {
        //   "name": "Martian - trusted Aptos wallet",
        //   "tags": "Wallet",
        //   "discord": "https://discord.gg/MQDnAjPN",
        //   "Published": "Jul 19, 2022 6:05 AM",
        //   "twitter": "https://twitter.com/martian_wallet",
        //   "status": "Testnet",
        //   "logo": "",
        //   "github": "",
        //   "Docs": "",
        //   "Npm": "",
        // },
        // {
        //   "name": "Topaz - Aptos NFT Marketplace",
        //   "tags": "Marketplace, NFTs",
        //   "discord": "",
        //   "Published": "Jul 19, 2022 5:45 AM",
        //   "twitter": "https://twitter.com/TopazMarket",
        //   "status": "Testnet",
        //   "logo": "",
        //   "github": "",
        //   "Docs": "",
        //   "Npm": "",
        // }
]
