export const dapps = [
        {
          "name": "Empo",
          "tags": "DEX, DeFi",
          "discord": "",
          "Published": "Jul 19, 2022 6:53 AM",
          "Twitter": "https://twitter.com/Empo_Fi",
          "status": "TBA",
          "logo": "",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "DEFI"
        },
        {
          "name": "WitchVerseLabs",
          "tags": "NFTs",
          "discord": "https://discord.gg/fdJXZE6F",
          "Published": "Jul 19, 2022 8:30 AM",
          "Twitter": "https://twitter.com/WitchVerseLabs",
          "status": "ongoing",
          "logo": "",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "NFT"
        },
        {
          "name": "NjordFinance",
          "tags": "DeFi",
          "discord": "",
          "Published": "Jul 27, 2022 12:42 PM",
          "Twitter": "https://twitter.com/NjordFinance",
          "status": "TBA",
          "logo": "",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "DEFI"
        },
        {
          "name": "Thala Labs",
          "tags": "DeFi",
          "discord": "",
          "Published": "Jul 21, 2022 7:50 PM",
          "Twitter": "https://twitter.com/ThalaLabs",
          "status": "TBA",
          "logo": "",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "DEXDEFI"
        },
        {
          "name": "1kx",
          "tags": "DeFi, Exchange",
          "discord": "",
          "Published": "Jul 28, 2022 9:59 AM",
          "Twitter": "https://twitter.com/1kxprotocol",
          "status": "Testnet",
          "logo": "",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "DEXDEFI"
        },
        {
          "name": "ultima",
          "tags": "DEX, Exchange",
          "discord": "",
          "Published": "Jul 19, 2022 6:18 AM",
          "Twitter": "https://twitter.com/ultimaprotocol",
          "status": "",
          "logo": "",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "NetworkDEFI"
        },
        {
          "name": "AptosLend",
          "tags": "Lending",
          "discord": "",
          "Published": "Jul 30, 2022 2:14 PM",
          "Twitter": "https://twitter.com/aptoslend",
          "status": "TBA",
          "logo": "",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "DEFILending"
        },
        {
          "name": "Pontem Network",
          "tags": "DEX, DeFi, Infrastructure, Tools",
          "discord": "https://discord.gg/kHWnQpBq",
          "Published": "Jul 19, 2022 5:48 AM",
          "Twitter": "https://twitter.com/PontemNetwork",
          "status": "Testnet",
          "logo": "",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "DEXNetwork"
        },
        {
          "name": "https://aptos.super.site/aptos-aptos-labs/zaptos-zero-fee-liquid-staking-on-aptos",
          "tags": "DeFi, Staking",
          "discord": "https://discord.gg/4cC28wbK",
          "Published": "Jul 19, 2022 6:05 AM",
          "Twitter": "https://twitter.com/ZaptosFinance",
          "status": "ongoing",
          "logo": "",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "DEFISTAKE"
        },
        {
          "name": "Hanson",
          "tags": "DeFi",
          "discord": "",
          "Published": "Jul 19, 2022 6:28 AM",
          "Twitter": "https://twitter.com/hansondotso",
          "status": "TBA",
          "logo": "",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "DEXDEFISTAKE"
        },
        {
          "name": "Laminar",
          "tags": "DEX, Orderbook",
          "discord": "https://discord.gg/h6Kx9pkp",
          "Published": "Jul 19, 2022 5:48 AM",
          "Twitter": "https://twitter.com/LaminarMarkets",
          "status": "TBA",
          "logo": "",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "DEXORDER"
        },
        {
          "name": "Tsunami Finance",
          "tags": "DeFi",
          "discord": "",
          "Published": "Jul 25, 2022 10:00 AM",
          "Twitter": "https://twitter.com/Tsunamifinance_",
          "status": "",
          "logo": "",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "DEFI"
        },
        {
          "name": "Switchboard",
          "tags": "Oracle",
          "discord": "",
          "Published": "Jul 19, 2022 6:28 AM",
          "Twitter": "https://twitter.com/switchboardxyz",
          "status": "TBA",
          "logo": "",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "ORACLE"
        },
        {
          "name": "Vial Protocol",
          "tags": "DeFi",
          "discord": "",
          "Published": "Jul 19, 2022 4:35 PM",
          "Twitter": "https://twitter.com/vialprotocol",
          "status": "Testnet",
          "logo": "",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "DEFI"
        },
        {
          "name": "names.aptos",
          "tags": "Name Service, Tools",
          "discord": "",
          "Published": "Jul 19, 2022 6:28 AM",
          "Twitter": "https://twitter.com/aptosnames",
          "status": "Testnet",
          "logo": "",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "NFTIdentity"
        },
        {
          "name": "Hippo Labs",
          "tags": "Aggregator, DeFi, Tools",
          "discord": "",
          "Published": "Jul 19, 2022 6:22 AM",
          "Twitter": "https://twitter.com/hippolabs__",
          "status": "",
          "logo": "",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "Network"
        },
        {
          "name": "Aries Market - Decentralised Margin Trading",
          "tags": "DeFi",
          "discord": "https://discord.gg/h6Kx9pkp",
          "Published": "Jul 19, 2022 6:05 AM",
          "Twitter": "https://twitter.com/AriesMarkets",
          "status": "TBA",
          "logo": "",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "PERPNetworkORDER"
        },
        {
          "name": "Fewcha Wallet - crypto wallet for Aptos",
          "tags": "Wallet",
          "discord": "https://discord.gg/HRbMWmhm",
          "Published": "Jul 19, 2022 5:45 AM",
          "Twitter": "https://twitter.com/FewchaWallet",
          "status": "Testnet",
          "logo": "",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "WALLET"
        },
        {
          "name": "Mariana Exchange",
          "tags": "DeFi, Exchange",
          "discord": "",
          "Published": "Jul 27, 2022 12:45 PM",
          "Twitter": "https://twitter.com/marianaexchange",
          "status": "TBA",
          "logo": "",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "DEXDEFI"
        },
        {
          "name": "Paymagic",
          "tags": "Dao",
          "discord": "",
          "Published": "Jul 19, 2022 6:28 AM",
          "Twitter": "https://twitter.com/paymagic_",
          "status": "TBA",
          "logo": "",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "DAO"
        },
        {
          "name": "Econia",
          "tags": "DeFi, Orderbook",
          "discord": "https://discord.gg/ydAeGtrW",
          "Published": "Jul 19, 2022 6:20 AM",
          "Twitter": "https://twitter.com/EconiaLabs",
          "status": "TBA",
          "logo": "",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "DEXORDERNetwork"
        },
        {
          "name": "Martian - trusted Aptos wallet",
          "tags": "Wallet",
          "discord": "https://discord.gg/MQDnAjPN",
          "Published": "Jul 19, 2022 6:05 AM",
          "Twitter": "https://twitter.com/martian_wallet",
          "status": "Testnet",
          "logo": "",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "WALLETNFT"
        },
        {
          "name": "Topaz - Aptos NFT Marketplace",
          "tags": "Marketplace, NFTs",
          "discord": "",
          "Published": "Jul 19, 2022 5:45 AM",
          "Twitter": "https://twitter.com/TopazMarket",
          "status": "Testnet",
          "logo": "",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "MARKET PLACENFT"
        }
]
