export const dapps = [
  // {
  //   "name": "Tsunami Finance",
  //   "tags": ["DeFi"],
  //   "description": "",
  //   "url": "https://tsunami.finance/",
  //   "discord": "",
  //   "Published": "Jul 25, 2022 10:00 AM",
  //   "twitter": "https://twitter.com/Tsunamifinance_",
  //   "status": "",
  //   "image": "tsunami.png",
  //   "github": "",
  //   "Docs": "",
  //   "Npm": "",
  //   "k": "DEFI"
  // },
  // {
  //   "name": "Switchboard",
  //   "tags": "Oracle",
  //   "discord": "",
  //   "Published": "Jul 19, 2022 6:28 AM",
  //   "twitter": "https://twitter.com/switchboardxyz",
  //   "status": "TBA",
  //   "logo": "",
  //   "github": "",
  //   "Docs": "",
  //   "Npm": "",
  //   "k": "ORACLE"
  // },

  {
    "name": "Econia",
    "description": "hyper-parallelized on-chain order book for the aptos blockchain",
    "tags": ["DeFi", "Orderbook"],
    "discord": "https://discord.gg/ydAeGtrW",
    "twitter": "https://twitter.com/EconiaLabs",
    "image": "econia.jpg",
    "status": "TBA",
    "github": "https://github.com/econia-labs",
    "docs": "https://www.econia.dev/",
    "address":"0xb1d4c0de8bc24468608637dfdbff975a0888f8935aa63338a44078eec5c7b6c7",
  },
  {
    "name": "Vial Protocol",
    "description": "",
    "tags": ["DeFi"],
    "url": "https://discord.com/invite/fMjZTVsSfe",
    "discord": "",
    "twitter": "https://twitter.com/vialprotocol",
    "status": "Testnet",
    "image": "vial.png",
    "github": "",
    "docs": "",
    "address":"0x1b6f1d8319f3f3b9649a4b2215a29c9184cb885c94e7eb51232a38ed6b28482c"
  },
  {
    "name": "names.aptos",
    "tags": ["Name Service", "Tools"],
    "discord": "",
    "Published": "Jul 19, 2022 6:28 AM",
    "twitter": "https://twitter.com/aptosnames",
    "status": "Testnet",
    "github": "",
    "image": "aptosnames.svg",
    "address":"0xf4eb1f3e838411ab992f81cabb25f29ea4eb2406cd167261273da587c3615792"
  },
  {
    "name": "Hippo Labs",
    "tags": ["Aggregator", "DeFi", "Tools"],
    "description": "",
    "discord": "",
    "twitter": "https://twitter.com/hippolabs__",
    "status": "",
    "image": "hippoLabs.jpeg",
    "github": "https://github.com/hippospace",
    "docs": "",
    "address":"0xa61e1e86e9f596e483283727d2739ba24b919012720648c29380f9cd0a96c11a"
  },
  {
    "name": "Souffl3",
    "tags": ["NFT"],
    "description": "",
    "discord": "",
    "twitter": "https://twitter.com/souffl3",
    "status": "",
    "image": "souffl3.jpg",
    "github": "",
    "docs": "",
    "address":"0xf6994988bd40261af9431cd6dd3fcf765569719e66322c7a05cc78a89cd366d4"

  },
  {
    "name": "Aries Market ",
    "description": "Decentralised Margin Trading",
    "tags": ["DeFi"],
    "url": "https://aries.market/",
    "discord": "https://discord.gg/h6Kx9pkp",
    "twitter": "https://twitter.com/AriesMarkets",
    "status": "testnet",
    "image": "aries.jpg",
    "github": "",
    "docs": "",
  },
  
        {
          "name": "Empo",
          discord: "",
          image: "empo.jpg",
          url: "",
          description:"",
          tags: ["DEX", "DeFi"],
          Published: "Jul 19, 2022 6:53 AM",
          twitter: "https://twitter.com/Empo_Fi",
          status: "TBA",
          github: "",
          Docs: "",
          Npm: "",
        },
        {
          name: "Zaptos",
          tags: ["DEX", "DeFi"],
          discord: "https://discord.gg/zaptos",
          image: "zaptos.jpg",
          url: "",
          description:"",
          twitter: "https://twitter.com/Empo_Fi",
          status: "TBA",
          github: "",
          Docs: "",
        },
        // {
        //   "name": "NjordFinance",
        //   "tags": "DeFi",
        //   "discord": "",
        //   "Published": "Jul 27, 2022 12:42 PM",
        //   "twitter": "https://twitter.com/NjordFinance",
        //   "status": "TBA",
        //   "logo": "",
        //   "Github": "",
        //   "Docs": "",
        //   "Npm": "",
        //   "k": "DEFI"
        // },
        // {
        //   "name": "Thala Labs",
        //   "tags": "DeFi",
        //   "discord": "",
        //   "Published": "Jul 21, 2022 7:50 PM",
        //   "twitter": "https://twitter.com/ThalaLabs",
        //   "status": "TBA",
        //   "logo": "",
        //   "Github": "",
        //   "Docs": "",
        //   "Npm": "",
        //   "k": "DEXDEFI"
        // },
        {
          "name": "1kx",
          "tags": ["DeFi", "Exchange"],
          "discord": "",
          "twitter": "https://twitter.com/1kxprotocol",
          "status": "Testnet",
          image: "1kx.jpg",
          "Github": "",
          "Docs": "",
          "Npm": "",
          "k": "DEXDEFI"
        },
        {
          "name": "ultima",
          "tags": ["DEX", "Exchange"],
          "discord": "",
          "twitter": "https://twitter.com/ultimaprotocol",
          "status": "",
          "image": "ultima.jpg",
          "github": "",
          "docs": "",
          "Npm": "",
        },
        {
          "name": "AptosLend",
          "tags": ["Lending"],
          "discord": "",
          "twitter": "https://twitter.com/aptoslend",
          "status": "TBA",
          "image": "aptosLend.png",
          "github": "",
          "Docs": "",
          "Npm": "",
        },
        {
          "name": "Pontem Network",
          "description": "",
          "tags": ["DEX", "DeFi", "Infrastructure", "Tools"],
          "discord": "https://discord.gg/kHWnQpBq",
          "twitter": "https://twitter.com/PontemNetwork",
          "status": "Testnet",
          "logo": "",
          "github": "",
          "url": "https://pontem.network/",
          "image": "pontemNetwork.jpg",
        },
        
        // {
        //   "name": "Hanson",
        //   "tags": ["DeFi"],
        //   "description": "",
        //   "discord": "",
        //   "twitter": "https://twitter.com/hansondotso",
        //   "status": "TBA",
        //   "image": "",
        //   "github": "",
        // },
        // {
        //   "name": "Laminar",
        //   "tags": ["DEX", "Orderbook"],
        //   "description": "",
        //   "discord": "https://discord.gg/h6Kx9pkp",
        //   "Published": "Jul 19, 2022 5:48 AM",
        //   "twitter": "https://twitter.com/LaminarMarkets",
        //   "status": "TBA",
        //   "logo": "",

        //   "github": "",
        //   "Docs": "",
        //   "Npm": "",
        //   "k": "DEXORDER"
        // },
        
        // {
        //   "name": "Mariana Exchange",
        //   "tags": "DeFi, Exchange",
        //   "discord": "",
        //   "Published": "Jul 27, 2022 12:45 PM",
        //   "twitter": "https://twitter.com/marianaexchange",
        //   "status": "TBA",
        //   "logo": "",
        //   "github": "",
        //   "Docs": "",
        //   "Npm": "",
        //   "k": "DEXDEFI"
        // },
        {
          "name": "Martian - trusted Aptos wallet",
          "tags": ["Wallet"],
          "discord": "https://discord.gg/MQDnAjPN",
          "twitter": "https://twitter.com/martian_wallet",
          "status": "Testnet",
          "logo": "",
          "github": "",
          "image":"martian.png",
          "docs": "",
        },
        {
          "name": "Fewcha",
          "tags": ["Wallet","Tools"],
          "description": "",
          "discord": "https://discord.gg/HRbMWmhm",
          "twitter": "https://twitter.com/FewchaWallet",
          "status": "Testnet",
          "image": "fewcha.svg",
          "github": "",
          "docs": "",
        },
        // {
        //   "name": "Topaz - Aptos NFT Marketplace",
        //   "tags": "Marketplace, NFTs",
        //   "discord": "",
        //   "Published": "Jul 19, 2022 5:45 AM",
        //   "twitter": "https://twitter.com/TopazMarket",
        //   "status": "Testnet",
        //   "logo": "",
        //   "github": "",
        //   "Docs": "",
        //   "Npm": "",
        // }
]
